[bitcoind]

[bitcoind.mainnet]
USERNAME = "bitcoin"
PASSWORD = "python"
HOST = "bitcoind.mooniversity.io"
PORT = 8332

[bitcoind.testnet]
USERNAME = "bitcoin"
PASSWORD = "python"
HOST = "bitcoind.mooniversity.io"
PORT = 18332

[btcd.mainnet]
USERNAME = "bitcoin"
PASSWORD = "python"
HOST = "btcd.mooniversity.io"
PORT = 8334

[btcd.testnet]
USERNAME = "bitcoin"
PASSWORD = "python"
HOST = "btcd.mooniversity.io"
PORT = 18334
