[bitcoind]

[bitcoind.mainnet]
TRANSPORT = "http"
USERNAME = "bitcoin"
PASSWORD = "python"
HOST = "68.183.110.103"
PORT = 8332

[bitcoind.testnet]
TRANSPORT = "http"
USERNAME = "bitcoin"
PASSWORD = "python"
HOST = "68.183.110.103"
PORT = 18332

[btcd.mainnet]
TRANSPORT = "https"
USERNAME = "bitcoin"
PASSWORD = "python"
HOST = "157.230.174.30"
PORT = 8334

[btcd.testnet]
TRANSPORT = "https"
USERNAME = "bitcoin"
PASSWORD = "python"
HOST = "157.230.174.30"
PORT = 18334
